## Transparent Machine Learning to Support Predicting COVID-19 Infection Risk Based on Chronic Diseases

*Authors: Hubert Ruczyński, Dawid Przybyliński, Kinga Ulasik*


### Abstract

The moment the Covid-19 outbreak in 2019 occured people started using machine learning in order to help in managing the situation. Our work is a continuation to research described in "An interpretable mortality prediction model for COVID-19 patients." "Predicting Mortality Due to SARS-CoV-2" and in "A Mechanistic Score Relating Obesity and Diabetes to COVID-19 Outcomes in Mexico" articles, we also used the same data in order to create our own models. We improved and created new models predicting Covid-19 mortality based on blood parameters and analyzed original models presented in the articles.We trained a predicion model with over 70% accuracy calculating risk of getting infected with the virus depending only on person's sex, age and chronic diseases and created an application which calculates the covid infection risk based on input data and explains the model with visulisations. Considering accuracy of the model, calculations based only on chronic dieases may not achieve best results but we propose an approch which doesnt need any additional medical information, is explainable and easy to understand and requires only data that everyone has access to. 



### Introduction


### Flaws of Chinese approach

### Improving Chinese model
#### Prediction using original parameters on external data
#### Better models for original data
#### Is model trained on Chinese data valid for predicting disease within other nations?

### Flaws of the approach
#### PCA
#### General drawbacks

#### Summary

### Mexican approach
#### Data
#### Research

### Application
#### Introduction

### Model
#### Features

#### Conclusions and Disccusion

### References



