
## Roshomon sets on death prediction XGB models using MIMIC-III database
*Authors: Ada Gąssowska, Elżbieta Jowik (Warsaw University of Techcnology)*

### An initial literature review
The Rashomon Effect is not a common concept, therefore all references to it in the literature are limited to some extent. In general it is said to occur when the same phenomenon can be explained in many different ways. The Rashomon set in turn is introduced as the set of almost-equally-accurate models for a given problem. With regard to Machine Learning the above term was first used by Leo Breiman in his 2001 paper [@6-0-breiman2001statistical] to describe a class of problems where many differing, accurate models exist to describe the same data i.e. to describe the case where we have many models that are different but are approximately-equally accurate.  
The name concept came from the title of the movie by Kurosawa from 1950 in which different characters have different perspectives on the same crimes. Breiman emphasized that the observation of many different accurate models on specific datasets is a common phenomenon.  
Since 2001 the topic was rarely discussed. While doing research on different machine learning models, data was quite often not taken into consideration at all. As stated in the recent article "A study in Rashomon curves and volumes: A new perspective on generalization and model simplicity in machine learning" [@6-0-rashomon-intro] Rashomon effect is directly linked to the topic of Interpretable Machine Learning. The authors mention that often when the Rashomon set is large it implies that there may be an explainable model that performs well on the dataset. In the paper they focus on analysing Rashomon effect on different datasets and trying to generalize the statements about what the size of Rashomons set tells us about the  machine learning problem. 
The other important topic connected to Rashomon effect is analysing the variable importance of the model. The question why models with similar performance on the dataset take different variables into considaration for prediction needs to be adressed. This area of research is described in an article called "All Models are Wrong, but Many are Useful: Learning a Variables' Importance by Studying an Entire Class of Prediction Models Simultaneously". [@6-0-rashomon-variable-importance] It is emphasised there that there are fields, for example criminal recidivism prediction, where Explainable Machine Learning (including Rashomon effect) is specially important, as the non-explainable models may rely on unacceptable data (sex, race etc). In another article [@6-0-rashomon-variable-importance-cloud] the authors emphasize the fact that only by comparing many models of similar performance the importance of a variable compared to other variables can be throughly understood. They present the concept of variable importance cloud and draw connection of it to other areas. They research showed that the variable importance may dramatically differ in approximately equally good models. 
